#!/usr/bin/env python3


import pathlib
import re
import sys

if len(sys.argv) != 2:
    raise SystemExit('usage: patch_android_sea_g2p_asset.py <android-app-dir>')

app = pathlib.Path(sys.argv[1])
path = app / 'src/main/java/com/vieneu/voiceclone/ModelManager.kt'
text = path.read_text(encoding='utf-8')

old = '''    fun modelDir(context: Context): File {
        val base = context.getExternalFilesDir(null) ?: context.filesDir
        return File(base, "vieneu-v3-turbo-native")
    }
'''
new = '''    fun modelDir(context: Context): File {
        val base = context.getExternalFilesDir(null) ?: context.filesDir
        val root = File(base, "vieneu-v3-turbo-native")
        root.mkdirs()
        ensureBundledSeaG2pDictionary(context, root)
        return root
    }

    private fun ensureBundledSeaG2pDictionary(context: Context, root: File) {
        val target = File(root, "sea_g2p.bin")
        if (target.isFile && target.length() > 0L) return

        val temporary = File(root, "sea_g2p.bin.part")
        context.assets.open("sea_g2p.bin").use { input ->
            temporary.outputStream().buffered().use { output -> input.copyTo(output) }
        }
        if (target.exists()) target.delete()
        if (!temporary.renameTo(target)) {
            temporary.copyTo(target, overwrite = true)
            temporary.delete()
        }
        check(target.isFile && target.length() > 0L) {
            "Không thể cài từ điển phát âm tiếng Việt sea-g2p."
        }
    }
'''

if new in text:
    print('Android sea-g2p dictionary install is already patched')
else:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(
            f'ModelManager.modelDir anchor: expected one match, found {count}'
        )
    path.write_text(text.replace(old, new, 1), encoding='utf-8')
    print('Patched Android sea-g2p dictionary install')


gradle = app / 'build.gradle.kts'
if not gradle.is_file():
    raise RuntimeError(f'Missing Android Gradle file: {gradle}')

# MainActivity is generated by the materialization pipeline. Patch the nullable
# AudioRecord read at the final pre-Gradle stage so Kotlin never has to smart-cast
# the mutable Activity property from inside the recording worker thread.
activity = app / 'src/main/java/com/vieneu/voiceclone/MainActivity.kt'
if activity.is_file():
    activity_text = activity.read_text(encoding='utf-8')
    activity_text, recorder_read_fixes = re.subn(
        r'(?<![?\w])recorder\.read\(([^()\n]+)\)',
        r'(recorder?.read(\1) ?: 0)',
        activity_text,
    )
    if recorder_read_fixes == 0 and 'recorder?.read(' not in activity_text:
        raise RuntimeError('AudioRecord smart-cast fix: generated recorder.read(...) call not found')
    activity.write_text(activity_text, encoding='utf-8')
    print(f'Patched generated AudioRecord nullable read ({recorder_read_fixes} replacement(s))')

    activity_lines = activity_text.splitlines()
    recorder_lines = [index for index, line in enumerate(activity_lines) if 'recorder' in line or 'AudioRecord' in line]
    if recorder_lines:
        print('Generated MainActivity AudioRecord context after patch:')
        emitted = set()
        for index in recorder_lines:
            for context_index in range(max(0, index - 3), min(len(activity_lines), index + 4)):
                if context_index in emitted:
                    continue
                emitted.add(context_index)
                print(f'MainActivity.kt:{context_index + 1}: {activity_lines[context_index]}')
    else:
        print('Generated MainActivity contains no recorder or AudioRecord references before Gradle build')
